"""Three-dimensional finite-sliding mortar contact research package."""

from .clipping import (
    ClippedPolygonLinearization,
    ClippingOperation,
    ClippingStage,
    ClippingTopology,
    ClippingTopologyError,
    FacetIntersectionLinearization,
    clip_convex_polygon_linearized,
    linearize_clipping_topology,
    linearize_facet_intersection,
    replay_clipping_topology,
    trace_clipping_topology,
)
from .contact import (
    ContactEvaluation,
    ContactPair,
    GlobalMortarWeights,
    assemble_mortar_weights,
    evaluate_contact,
    fixed_mortar_contact_tangent,
    numerical_contact_tangent,
)
from .geometry import (
    clip_convex_polygon,
    facet_projection_plane,
    facet_projection_plane_jacobian,
    polygon_signed_area,
    project_to_plane,
    project_to_plane_jacobian,
    triangulate_convex_polygon,
)
from .model import (
    FacetOverlap,
    LocalMortarWeights,
    MortarPallet,
    ProjectedPointsJacobian,
    ProjectionPlane,
    ProjectionPlaneJacobian,
)
from .moving import (
    MortarWeightJacobian,
    moving_mortar_contact_tangent,
    numerical_mortar_weight_jacobian,
)
from .overlap import build_facet_overlap, integrate_facet_pair
from .pallets import (
    FacetPalletLinearization,
    MortarPalletLinearization,
    PalletFanLinearization,
    PalletTopologyError,
    SignedAreaLinearization,
    linearize_centroid_fan,
    linearize_facet_pallets,
    polygon_signed_area_linearized,
)
from .shapes import infer_facet_kind, inverse_map_2d, shape_values
from .surface import (
    ContactSurface,
    averaged_nodal_normal_jacobian,
    averaged_nodal_normals,
    discover_facet_pairs,
)

__all__ = [
    "ClippedPolygonLinearization",
    "ClippingOperation",
    "ClippingStage",
    "ClippingTopology",
    "ClippingTopologyError",
    "ContactEvaluation",
    "ContactPair",
    "ContactSurface",
    "FacetIntersectionLinearization",
    "FacetOverlap",
    "FacetPalletLinearization",
    "GlobalMortarWeights",
    "LocalMortarWeights",
    "MortarPallet",
    "MortarPalletLinearization",
    "MortarWeightJacobian",
    "PalletFanLinearization",
    "PalletTopologyError",
    "ProjectedPointsJacobian",
    "ProjectionPlane",
    "ProjectionPlaneJacobian",
    "SignedAreaLinearization",
    "assemble_mortar_weights",
    "averaged_nodal_normal_jacobian",
    "averaged_nodal_normals",
    "build_facet_overlap",
    "clip_convex_polygon",
    "clip_convex_polygon_linearized",
    "discover_facet_pairs",
    "evaluate_contact",
    "facet_projection_plane",
    "facet_projection_plane_jacobian",
    "fixed_mortar_contact_tangent",
    "infer_facet_kind",
    "integrate_facet_pair",
    "inverse_map_2d",
    "linearize_centroid_fan",
    "linearize_clipping_topology",
    "linearize_facet_intersection",
    "linearize_facet_pallets",
    "moving_mortar_contact_tangent",
    "numerical_contact_tangent",
    "numerical_mortar_weight_jacobian",
    "polygon_signed_area",
    "polygon_signed_area_linearized",
    "project_to_plane",
    "project_to_plane_jacobian",
    "replay_clipping_topology",
    "shape_values",
    "trace_clipping_topology",
    "triangulate_convex_polygon",
]
