"""Nonlinear and linear solution algorithms for coupled contact problems."""

from .augmented import solve_augmented_contact
from .continuation import (
    AdaptiveAcceptedStep,
    AdaptiveAttemptAction,
    AdaptiveContactAttempt,
    AdaptiveContactOptions,
    AdaptiveContactResult,
    AdaptiveLoadOptions,
    AdaptivePenaltyOptions,
    AdaptiveSolver,
    AdaptiveTerminationReason,
    contact_penalties,
    solve_adaptive_contact_path,
    with_contact_penalties,
)
from .linear import (
    LinearBackend,
    LinearPreconditioner,
    LinearSolveDiagnostics,
    LinearSolveResult,
    LinearSolverOptions,
    PreconditionerFactory,
    PreconditionerKind,
    block_jacobi_preconditioner_factory,
    extract_csr_submatrix,
    field_split_preconditioner_factory,
    solve_linear_system,
    solve_reduced_system,
)
from .newton import solve_coupled_equilibrium, solve_equilibrium, solve_load_steps
from .results import (
    AugmentationIteration,
    AugmentedContactOptions,
    AugmentedContactResult,
    AugmentedTerminationReason,
    ContactEventPolicy,
    CoupledNewtonIteration,
    CoupledNewtonResult,
    CoupledTerminationReason,
    NewtonIteration,
    NewtonOptions,
    NewtonResult,
    TerminationReason,
)
from .scaling import (
    ScaleAwareAugmentationIteration,
    ScaleAwareAugmentedContactResult,
    ScaleAwareNewtonIteration,
    solve_scale_aware_augmented_contact,
)

__all__ = [
    "AdaptiveAcceptedStep",
    "AdaptiveAttemptAction",
    "AdaptiveContactAttempt",
    "AdaptiveContactOptions",
    "AdaptiveContactResult",
    "AdaptiveLoadOptions",
    "AdaptivePenaltyOptions",
    "AdaptiveSolver",
    "AdaptiveTerminationReason",
    "AugmentationIteration",
    "AugmentedContactOptions",
    "AugmentedContactResult",
    "AugmentedTerminationReason",
    "ContactEventPolicy",
    "CoupledNewtonIteration",
    "CoupledNewtonResult",
    "CoupledTerminationReason",
    "LinearBackend",
    "LinearPreconditioner",
    "LinearSolveDiagnostics",
    "LinearSolveResult",
    "LinearSolverOptions",
    "NewtonIteration",
    "NewtonOptions",
    "NewtonResult",
    "PreconditionerFactory",
    "PreconditionerKind",
    "ScaleAwareAugmentationIteration",
    "ScaleAwareAugmentedContactResult",
    "ScaleAwareNewtonIteration",
    "TerminationReason",
    "block_jacobi_preconditioner_factory",
    "contact_penalties",
    "extract_csr_submatrix",
    "field_split_preconditioner_factory",
    "solve_adaptive_contact_path",
    "solve_augmented_contact",
    "solve_coupled_equilibrium",
    "solve_equilibrium",
    "solve_linear_system",
    "solve_load_steps",
    "solve_reduced_system",
    "solve_scale_aware_augmented_contact",
    "with_contact_penalties",
]
